# Basic Python

## 1. Split this string

In [2]:
s = "Hi there Sam!"

In [3]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
print('The diameter of {} is {} kilometers.'.format(planet,diameter))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [7]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
d['k1'][3]['tricky'][3]['target'][3]

'hello'

# Numpy

In [8]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [9]:
import numpy as np
print('An array of 10 Zeros:')
np.zeros(10)

An array of 10 Zeros:


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
print('An array of 10 fives:')
np.ones(10)*5

An array of 10 fives:


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [13]:
# or we can print the even integer as follow
print (np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [14]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [15]:
a=np.array([1,2,3])
b=np.array([4,5,6])
i=np.concatenate((a,b))
print(i)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [22]:
import pandas as pd

In [23]:
# intialize data
data=[['POOJA','CSE',89],['SUJI','CSE',90]]
df=pd.DataFrame(data,columns=['Name','Dept','marks'])
#print df
df

Name Dept  marks
0  POOJA  CSE     89
1   SUJI  CSE     90

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [28]:
import pandas as pd
c=pd.date_range("01-01-2023","10-02-2023")
d=pd.Series(c)
print("The series of date from 1st Jan,23 to 10 Feb,23")
d

The series of date from 1st Jan,23 to 10 Feb,23


0     2023-01-01
1     2023-01-02
2     2023-01-03
3     2023-01-04
4     2023-01-05
         ...    
270   2023-09-28
271   2023-09-29
272   2023-09-30
273   2023-10-01
274   2023-10-02
Length: 275, dtype: datetime64[ns]

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [29]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [32]:
import pandas as pd
lists=[[1,'aaa',11],[2,'bbb',13],[3,'ccc',14]]
df=pd.DataFrame(lists)
#print df 
df

0    1   2
0  1  aaa  11
1  2  bbb  13
2  3  ccc  14